/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dairy.management;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ajay
 */
public class login extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        seticon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_lbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_user = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        lgoin_btn = new javax.swing.JButton();
        bg_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dairy Management System");
        setBackground(new java.awt.Color(255, 0, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(715, 482));
        setResizable(false);
        getContentPane().setLayout(null);

        login_lbl.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        login_lbl.setText("             Dairy Management System");
        login_lbl.setToolTipText("");
        getContentPane().add(login_lbl);
        login_lbl.setBounds(0, 0, 700, 90);

        jPanel1.setBackground(new java.awt.Color(242, 241, 241));

        lbl_user.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_user.setForeground(new java.awt.Color(255, 102, 0));
        lbl_user.setText("Username:");
        lbl_user.setToolTipText("");
        lbl_user.setAlignmentX(1.0F);
        lbl_user.setAlignmentY(1.0F);

        username.setBackground(new java.awt.Color(204, 204, 204));
        username.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        username.setToolTipText("Enter Username");
        username.setActionCommand("<Not Set>");
        username.setAlignmentX(1.0F);
        username.setAlignmentY(1.0F);
        username.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        lbl_password.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(255, 102, 0));
        lbl_password.setText("Password:");

        password.setBackground(new java.awt.Color(204, 204, 204));
        password.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        password.setToolTipText("Enter Password");
        password.setAlignmentX(1.0F);
        password.setAlignmentY(1.0F);
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        lgoin_btn.setBackground(new java.awt.Color(255, 153, 51));
        lgoin_btn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lgoin_btn.setForeground(new java.awt.Color(51, 51, 51));
        lgoin_btn.setText("Login");
        lgoin_btn.setToolTipText("Click here to login");
        lgoin_btn.setAutoscrolls(true);
        lgoin_btn.setBorder(null);
        lgoin_btn.addActionListener(this);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_user, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lgoin_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(lbl_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lgoin_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        username.getAccessibleContext().setAccessibleName("");
        lgoin_btn.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, 90, 690, 350);

        bg_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg.jpg"))); // NOI18N
        bg_lbl.setToolTipText("");
        bg_lbl.setMaximumSize(new java.awt.Dimension(800, 554));
        bg_lbl.setMinimumSize(new java.awt.Dimension(800, 554));
        bg_lbl.setPreferredSize(new java.awt.Dimension(800, 554));
        getContentPane().add(bg_lbl);
        bg_lbl.setBounds(0, 0, 700, 445);

        pack();
        setLocationRelativeTo(null);
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == lgoin_btn) {
            login.this.lgoin_btnActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void lgoin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgoin_btnActionPerformed
       String user=username.getText();
       String pass=password.getText(); 
        if ("".equals(user) || "".equals(pass))
            JOptionPane.showMessageDialog(null, "Fill the Login Details");
        else
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/dms","DMS","Dairy@123");
                String str="Select * from login where username=? and password=?";
                PreparedStatement pst=con.prepareStatement(str);
                pst.setString(1,username.getText());
                pst.setString(2,password.getText());
                ResultSet rs=pst.executeQuery();
                if(rs.next()){
                    Dashboard menu=new Dashboard();
                    menu.setVisible(true);
                    setVisible(false);  
                }
                else{
                    JOptionPane.showMessageDialog(null,"Username and Password INVALID");
                    username.setText("");
                    password.setText("");
                }
                con.close();
            }
            catch(HeadlessException | ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(null,e);
            }
    }//GEN-LAST:event_lgoin_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      splash sp=new splash();
        sp.setVisible(true);
        login lg=new login();
        try{
                    for(int i=0;i<=100;i++)
                    {
                        Thread.sleep(30);
                        sp.label2.setText(Integer.toString(i)+"%");
                        sp.jProgressBar3.setValue(i);
                        if(i == 100){
                            sp.setVisible(false);
                            lg.setVisible(true);
                        }        
                    }
            
        }
        catch(Exception e){
                    
        }
        
        
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new login().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_lbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JButton lgoin_btn;
    private javax.swing.JLabel login_lbl;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private void seticon() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("1232.jpg")));
    }
}
